project:
  type: book
  output-dir: docs

profile:
  default: book
  group:
    - [book, slides]

book:
  title: "My Book"
  author: "Ralph-Uwe BÃ¶rner"
  chapters:
    - index.qmd
    - history.qmd
    - methods.qmd
    - slidedecks.qmd

format: 
  html:
    theme: cosmo
    number-sections: true
    lib-dir: site_libs
    include-in-header:
      - text: |
          <script>
          window.MathJax = {
            loader: {
              load: ['[tex]/physics']
            },
            tex: {
              packages: {'[+]': ['physics']}
            }
          };
          </script>

editor: source